Help me figure out what is going on with my attempts to use f2py!!

To reproduce my problems:

python 2.7.8
gfortran

f2py -c -m flintstone flintstone.pyf callback.f nocallback.f

ipython> run cb.py

I get the following output:

 Yabba Dabba Doo!
fred!
bambam: I want 4 Brontosaurus Burgers!
 barney
 Yabba Dabba Doo!
fred!
capi_return is NULL
Call-back cb_bambam_in_test__user__routines failed.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/deen/Code/Python/sandbox/fluffy-kumquat/cb.py in <module>()
     12 
     13 flintstone.test()
---> 14 flintstone.barney()
     15 
     16 

TypeError: bambam() takes exactly 1 argument (0 given)

The output suggests that the bambam(n) callback in the test subroutine in callback.f 
works when it is called directly from the python routine, but not when it is called
indirectly from the barney subroutine in nocallback.f

Any and all suggestions are welcome!  Thanks for taking the time to look!

Cheers,
Casey

